name: CI-dev

on:
  push:
    branches:
      - dev

jobs:
  build_catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image of Catalog
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} # Variable ajouté dans github
          APP_NAME: ${{ 'exempleapi-heroku' }} # Nom de l'application heroku
        run: |
          cd ./src/Catalog 
          docker build -f Dockerfile . 